### ISSUE TITLE
USER STORY: Recording previous polls on Love Running

### ISSUE THREAD

**Issue by StephHjar** [StephHjar/My-First-Agile-Project#6]
As a **website administrator** I can **access the results of previous polls** so that **I can understand users' preferences**

## Acceptance Criteria

- Acceptance Criteria 1: Each poll's results are written to a database or sheet
- Acceptance Criteria 2: The administrator has access to the data

## Tasks

- [ ] Update poll functionality so that votes are recorded to a Google Sheet when the user presses 'Submit'
- [ ] Create a new tab on the Sheet for each poll
- [ ] Test the functionality
