### ISSUE TITLE
USER STORY: Unpublishing a poll on Love Running

### ISSUE THREAD

**Issue by StephHjar** [StephHjar/My-First-Agile-Project#7]
As a **website administrator** I can **unpublish a poll** so that **the final results can be tallied**

## Acceptance Criteria

- Acceptance Criteria 1: The website administrator can decide when a poll should be unpublished
- Acceptance Criteria 2: The poll is automatically closed at that time
- Acceptance Criteria 3: After the poll is closed, results are displayed on the home page

## Tasks

- [ ] Update the poll builder code to allow an expiry date to be set
- [ ] Remove the poll from the website at that time so that no new votes can be accepted
- [ ] Update the website to display poll results after the expiry date
- [ ] Test the functionality
